artifacts_root: "artifacts"

dataingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "hf://datasets/inGeniia/german-credit-risk_credit-scoring_mlp/german_credit_risk.csv"
  local_data_file: "artifacts/data_ingestion/german_credit_risk.csv"
  unzip_dir: "artifacts/data_ingestion"

data_validation:
  root_dir: "artifacts/data_ingestion"
  local_data_file: "artifacts/data_ingestion/german_credit_risk.csv"
  status_folder: "artifacts/data_validation"
  status_file: "artifacts/data_validation/status.txt"



data_transformation:
  local_data_file: "artifacts/data_ingestion/german_credit_risk.csv"
  root_dir_train: artifacts/train
  root_dir_test: artifacts/test
  train_dir: artifacts/train/training_set.csv
  test_dir : artifacts/test/test_set.csv
  test_size: 0.2
  random_state: 50



model_trainer:
  training_set : artifacts/train/training_set.csv
  droped_column: "Unnamed: 0"
  target_columns: Risk
  test_size : 0.25
  model_dir: artifacts/model
  model_path: artifacts/model/model.pkl


model_evaluation:
  model_path: artifacts/model/model.pkl
  test_set : artifacts/test/test_set.csv
  droped_column: "Unnamed: 0"
  target_columns: Risk
